with catalog(name, category, primary_muscles, secondary_muscles, equipment, instructions, safety_notes) as (
  values
    ('Sentadilla', 'strength', array['cuadriceps','gluteos'], array['isquios','core'], 'barra', 'Baja con control, torso firme y pies estables. Progresar carga solo con tecnica consistente.', 'Evitar dolor agudo de rodilla o espalda. Ajustar rango.'),
    ('Press de banca', 'strength', array['pecho','triceps'], array['hombros'], 'barra', 'Escapulas estables, pies firmes y empuje controlado.', 'Usar spotter o seguros con cargas altas.'),
    ('Peso muerto rumano', 'strength', array['isquios','gluteos'], array['espalda','core'], 'barra o mancuernas', 'Bisagra de cadera, espalda neutra y recorrido controlado.', 'No redondear espalda ni perseguir rango a costa de tecnica.'),
    ('Dominadas asistidas', 'strength', array['espalda','biceps'], array['core'], 'maquina o banda', 'Tira los codos hacia abajo y controla la subida.', 'Usar asistencia suficiente para evitar balanceo.'),
    ('Remo con barra', 'strength', array['espalda','biceps'], array['core'], 'barra', 'Torso firme, tira hacia abdomen y controla la bajada.', 'Evitar tirones si la espalda lumbar se fatiga.'),
    ('Hip thrust', 'strength', array['gluteos'], array['isquios','core'], 'barra o maquina', 'Empuja la cadera hasta extension completa sin arquear lumbar.', 'Usar almohadilla y controlar pelvis.'),
    ('Press militar con barra', 'strength', array['hombros','triceps'], array['core'], 'barra', 'Empuja vertical, costillas abajo y gluteos firmes.', 'Evitar si genera dolor de hombro o espalda.'),
    ('Sentadilla frontal', 'strength', array['cuadriceps','gluteos'], array['core'], 'barra', 'Torso vertical, codos altos y rango controlado.', 'Requiere movilidad de muneca/hombro; ajustar si molesta.'),
    ('Peso muerto convencional', 'strength', array['gluteos','isquios','espalda'], array['core'], 'barra', 'Barra cerca del cuerpo, empuja el piso y bloquea con gluteos.', 'Ejercicio tecnico; no maximizar sin supervision.'),
    ('Trap bar deadlift', 'strength', array['gluteos','cuadriceps','isquios'], array['core'], 'trap bar', 'Centro de masa dentro de la barra, empuja el piso con postura firme.', 'Mantener espalda neutra.'),
    ('Press inclinado con mancuernas', 'strength', array['pecho','hombros','triceps'], array[]::text[], 'mancuernas', 'Baja con control y empuja siguiendo trayectoria natural.', 'Evitar rango doloroso de hombro.'),
    ('Press de hombros con mancuernas', 'strength', array['hombros','triceps'], array['core'], 'mancuernas', 'Empuja arriba sin arquear lumbar y controla bajada.', 'Ajustar agarre si hay molestia.'),
    ('Jalon al pecho', 'strength', array['espalda','biceps'], array[]::text[], 'polea', 'Pecho alto, codos hacia abajo y subida controlada.', 'No tirar detras de la nuca si molesta.'),
    ('Prensa de piernas', 'strength', array['cuadriceps','gluteos'], array['isquios'], 'maquina', 'Baja con control y empuja sin bloquear rodillas.', 'No despegar pelvis del respaldo.'),
    ('Split squat bulgaro', 'strength', array['cuadriceps','gluteos'], array['core'], 'mancuernas', 'Pie delantero estable, baja vertical y sube con control.', 'Comenzar liviano por demanda de equilibrio.'),
    ('Remo sentado en polea', 'strength', array['espalda','biceps'], array[]::text[], 'polea', 'Tira hacia abdomen, pecho alto y escapulas activas.', 'Evitar balanceo excesivo.'),
    ('Remo pecho apoyado', 'strength', array['espalda','biceps'], array[]::text[], 'maquina o banco', 'Apoya pecho y tira con codos hacia atras.', 'Ajustar altura para no elevar hombros.'),
    ('Curl femoral sentado', 'strength', array['isquios'], array[]::text[], 'maquina', 'Flexiona rodilla con control y pausa breve.', 'Ajustar eje de maquina con rodilla.'),
    ('Hack squat', 'strength', array['cuadriceps','gluteos'], array[]::text[], 'maquina', 'Espalda apoyada, rodillas siguen linea de pies.', 'No bloquear rodillas.'),
    ('Jalon agarre neutro', 'strength', array['espalda','biceps'], array[]::text[], 'polea', 'Agarre neutro, codos abajo y pecho alto.', 'No usar impulso.'),
    ('Press en maquina convergente', 'strength', array['pecho','triceps'], array['hombros'], 'maquina', 'Ajusta asiento y empuja con control.', 'No perder contacto con respaldo.'),
    ('Remo con mancuerna a una mano', 'strength', array['espalda','biceps'], array['core'], 'mancuerna', 'Apoyo estable, tira el codo hacia la cadera.', 'Evitar rotar tronco de forma brusca.'),
    ('Remo en maquina convergente', 'strength', array['espalda','biceps'], array[]::text[], 'maquina', 'Ajusta apoyo y tira con control.', 'Mantener hombros lejos de orejas.'),
    ('Elevaciones laterales en polea', 'strength', array['hombros'], array[]::text[], 'polea', 'Eleva brazo en plano comodo hasta cerca de hombro.', 'Usar carga ligera y control.'),
    ('Elevaciones laterales con mancuernas', 'strength', array['hombros'], array[]::text[], 'mancuernas', 'Eleva con codos suaves y control.', 'No balancear el cuerpo.'),
    ('Fondos en paralelas asistidos', 'strength', array['pecho','triceps'], array['hombros'], 'maquina o banda', 'Baja en rango comodo y empuja sin colapsar hombros.', 'Evitar si hay dolor anterior de hombro.'),
    ('Press inclinado en maquina', 'strength', array['pecho','hombros','triceps'], array[]::text[], 'maquina', 'Ajusta asiento, empuja y controla el regreso.', 'No bloquear codos con fuerza.'),
    ('Zancadas caminando', 'strength', array['cuadriceps','gluteos'], array['core'], 'mancuernas', 'Paso controlado, rodilla sigue linea del pie.', 'Comenzar con poco peso.'),
    ('Press cerrado', 'strength', array['triceps','pecho'], array['hombros'], 'barra', 'Agarre comodo, codos controlados y empuje firme.', 'No cerrar demasiado el agarre.'),
    ('Face pull', 'strength', array['hombros','espalda'], array[]::text[], 'polea', 'Tira hacia rostro con codos altos y escapulas activas.', 'Carga ligera y controlada.'),
    ('Pallof press', 'strength', array['core'], array[]::text[], 'polea o banda', 'Resiste rotacion y extiende brazos lentamente.', 'Mantener pelvis estable.'),
    ('Press de piernas unilateral', 'strength', array['cuadriceps','gluteos'], array[]::text[], 'maquina', 'Un pie en plataforma, baja controlado y empuja sin bloqueo.', 'Ajustar recorrido por comodidad de rodilla.'),
    ('Sentadilla goblet', 'strength', array['cuadriceps','gluteos'], array['core'], 'mancuerna o kettlebell', 'Sostiene peso al pecho y baja con torso firme.', 'Excelente para aprender tecnica.'),
    ('Plancha', 'strength', array['core'], array['gluteos'], 'peso corporal', 'Cuerpo en linea, abdomen y gluteos activos.', 'Detener si hay dolor lumbar.'),
    ('Step-up con mancuernas', 'strength', array['cuadriceps','gluteos'], array['core'], 'mancuernas', 'Sube con control empujando el pie sobre la plataforma.', 'Usar altura que permita control.'),
    ('Glute bridge', 'strength', array['gluteos'], array['isquios'], 'peso corporal o barra', 'Empuja cadera y contrae gluteos arriba.', 'Evitar arquear lumbar.'),
    ('Curl con barra', 'strength', array['biceps'], array[]::text[], 'barra', 'Codos estables y recorrido controlado.', 'No balancear tronco.'),
    ('Extension de triceps en polea', 'strength', array['triceps'], array[]::text[], 'polea', 'Codos fijos y extension completa controlada.', 'No mover hombros para ayudar.'),
    ('Dead bug', 'strength', array['core'], array[]::text[], 'peso corporal', 'Mantiene zona lumbar estable mientras alternas brazos y piernas.', 'Reducir rango si se arquea espalda.'),
    ('Farmer carry', 'strength', array['core','espalda'], array['antebrazo'], 'mancuernas', 'Camina con postura alta y carga estable.', 'No inclinar tronco.'),
    ('Sentadilla smith', 'strength', array['cuadriceps','gluteos'], array[]::text[], 'maquina', 'Ubica pies comodos y baja controlado.', 'Ajustar posicion para no forzar rodillas.'),
    ('Extension de cuadriceps', 'strength', array['cuadriceps'], array[]::text[], 'maquina', 'Extiende rodilla con control y pausa breve.', 'Ajustar maquina al eje de rodilla.'),
    ('Elevacion de piernas colgado', 'strength', array['core'], array[]::text[], 'barra', 'Eleva piernas sin balanceo excesivo.', 'Progresar desde rodillas flexionadas.'),
    ('Elevacion de gemelos de pie', 'strength', array['pantorrillas'], array[]::text[], 'maquina', 'Sube y baja con rango completo.', 'Pausar abajo y arriba.'),
    ('Kettlebell swing', 'strength', array['gluteos','isquios'], array['core'], 'kettlebell', 'Bisagra explosiva de cadera, brazos relajados.', 'Aprender tecnica antes de subir carga.'),
    ('Crunch en polea', 'strength', array['core'], array[]::text[], 'polea', 'Flexiona tronco con control y pelvis estable.', 'No tirar con brazos.'),
    ('Curl inclinado con mancuernas', 'strength', array['biceps'], array[]::text[], 'mancuernas', 'Mantiene brazos atras y flexiona con control.', 'No hiperextender hombro.'),
    ('Curl femoral acostado', 'strength', array['isquios'], array[]::text[], 'maquina', 'Flexiona rodilla y controla regreso.', 'Ajustar apoyo y eje.'),
    ('Curl predicador', 'strength', array['biceps'], array[]::text[], 'banco predicador', 'Brazo apoyado y flexion controlada.', 'No bloquear codo agresivamente abajo.'),
    ('Extension francesa', 'strength', array['triceps'], array[]::text[], 'barra o mancuernas', 'Codos relativamente fijos y baja tras la cabeza.', 'Evitar si molesta el codo.'),
    ('Pajaro con mancuernas', 'strength', array['hombros','espalda'], array[]::text[], 'mancuernas', 'Inclina torso y abre brazos con control.', 'Carga ligera.'),
    ('Elevacion de gemelos sentado', 'strength', array['pantorrillas'], array[]::text[], 'maquina', 'Sube y baja con rango completo sentado.', 'Controlar rebote.'),
    ('Curl martillo', 'strength', array['biceps'], array['antebrazo'], 'mancuernas', 'Agarre neutro y codos estables.', 'Evitar balanceo.'),
    ('Aperturas en polea', 'strength', array['pecho'], array[]::text[], 'polea', 'Junta brazos en arco comodo y controla apertura.', 'No estirar mas alla de comodidad.'),
    ('Pull through en polea', 'strength', array['gluteos','isquios'], array[]::text[], 'polea', 'Bisagra de cadera y extension con gluteos.', 'Mantener espalda neutra.'),
    ('Pullover en polea', 'strength', array['espalda'], array[]::text[], 'polea', 'Brazos casi rectos, lleva la barra hacia muslos.', 'No compensar con lumbar.'),
    ('Patada de gluteo en polea', 'strength', array['gluteos'], array[]::text[], 'polea', 'Extiende cadera con pelvis estable.', 'Evitar arquear espalda.'),
    ('Buenos dias', 'strength', array['isquios','gluteos'], array['espalda'], 'barra', 'Bisagra de cadera con barra y control.', 'Ejercicio tecnico; no usar pesado sin experiencia.'),
    ('Abduccion de cadera en maquina', 'strength', array['gluteos'], array[]::text[], 'maquina', 'Abre piernas con control y pausa breve.', 'Complementario, no base de rutina.'),
    ('Pec deck', 'strength', array['pecho'], array[]::text[], 'maquina', 'Junta brazos con control y sin dolor.', 'Ajustar rango de hombro.'),
    ('Encogimientos de hombros', 'strength', array['espalda'], array[]::text[], 'mancuernas o barra', 'Eleva hombros y controla bajada.', 'Complementario para trapecio.'),
    ('Curl concentrado', 'strength', array['biceps'], array[]::text[], 'mancuerna', 'Apoya brazo y flexiona con control.', 'Finalizador, no prioritario.'),
    ('Aduccion de cadera en maquina', 'strength', array['gluteos'], array[]::text[], 'maquina', 'Cierra piernas con control.', 'Accesorio situacional.'),
    ('Elevacion frontal con mancuernas', 'strength', array['hombros'], array[]::text[], 'mancuernas', 'Eleva al frente con carga ligera.', 'No suele ser prioridad si ya hay presses.'),
    ('Fondos en banco', 'strength', array['triceps'], array['hombros'], 'banco', 'Baja solo en rango comodo y empuja.', 'Puede molestar hombros; priorizar opciones mas seguras.'),
    ('Abdominales en maquina', 'strength', array['core'], array[]::text[], 'maquina', 'Flexiona tronco con control.', 'No usar impulso.'),
    ('Remo al menton', 'strength', array['hombros'], array[]::text[], 'barra o polea', 'Tira en rango comodo con agarre amplio.', 'Puede molestar hombros; usar con cautela.'),
    ('Patada de triceps con mancuerna', 'strength', array['triceps'], array[]::text[], 'mancuerna', 'Extiende codo manteniendo brazo estable.', 'Finalizador, menos progresable.'),
    ('Press tras nuca', 'strength', array['hombros','triceps'], array[]::text[], 'barra', 'No recomendado por defecto; requiere movilidad y tecnica.', 'Evitar si hay dolor de hombro o cuello.')
)
insert into public.exercises
  (name, category, primary_muscles, secondary_muscles, equipment, instructions, safety_notes)
select
  c.name,
  c.category,
  c.primary_muscles,
  c.secondary_muscles,
  c.equipment,
  c.instructions,
  c.safety_notes
from catalog c
where not exists (
  select 1
  from public.exercises e
  where lower(e.name) = lower(c.name)
);
